#!/bin/sh
echo "$(figlet MW - CLI)"
echo "- By Amoghavarsha @TheAmoghavarsha \n"
echo "DISCLAIMER: SEARCH FOR YOUR FAVOURITE WORD IN lower case\n"
echo "Type the word: "
read word
curl -s https://www.merriam-webster.com/dictionary/$word | grep -E "<title>" | sed -e 's/Meaning - Merriam-Webster//g' -e 's/ &amp;//g' -e 's/<title>//g' -e 's/<\/title>//g' -e 's/Merriam-Webster//g' -e 's/Logo//g' -e 's/Menu Toggle//g' -e 's/<svg xmlns="http:\/\/www.w3.org\/2000\/svg" width="82" height="82" viewBox="0 0 41 41" fill="none" class="svg menu-mob-logo replaced-svg">//g' -e '1,4d'

curl -s https://www.merriam-webster.com/dictionary/$word | grep -E -m5 "content=" | tail -n1 | sed -e 's/<meta name="description" content="//g' -e 's/">//g' -e 's/How to use//g' -e 's/in a sentence.//g' -e 's/Synonym Discussion of//g' -e 's/$word//g' -e 's/<meta name="robots" content="noindex, nofollow//g'

echo "Do you want to know more? [y/n]" 
read more
if [ "$more" = "y" ]; then
curl -s https://www.merriam-webster.com/dictionary/$word | grep -E "<title>" | sed -e 's/Meaning - Merriam-Webster//g' -e 's/ &amp;//g' -e 's/<title>//g' -e 's/<\/title>//g' -e 's/Merriam-Webster//g' -e 's/Logo//g' -e 's/Menu Toggle//g' -e 's/<svg xmlns="http:\/\/www.w3.org\/2000\/svg" width="82" height="82" viewBox="0 0 41 41" fill="none" class="svg menu-mob-logo replaced-svg">//g' -e '1,4d'

curl -s https://www.merriam-webster.com/thesaurus/$word | grep -E -m5 "content=" | tail -n1 | sed -e  's/<meta name="description" content="//g' -e 's/">//g' -e 's/<meta name="robots" content="noindex, nofollow//g' 

fi
