#!/bin/sh
echo "$(figlet Merriam-Webster)"
echo "- By Amoghavarsha"
echo "DISCLAIMER: SEARCH FOR YOUR FAVOURITE WORD IN lower case\n"
echo "Type the word: "
read word
curl -s https://www.merriam-webster.com/dictionary/$word | grep -E "<title>" | sed 's/Meaning - Merriam-Webster//g' | sed 's/ &amp;//g' | sed 's/<title>//g' | sed 's/<\/title>//g'

curl -s https://www.merriam-webster.com/dictionary/$word | grep -E -m5 "content=" | tail -n1 | sed 's/<meta name="description" content="//g' | sed 's/">//g' | sed 's/How to use//g' | sed 's/in a sentence.//g' | sed 's/Synonym Discussion of//g' | sed 's/$word//g' | sed 's/<meta name="robots" content="noindex, nofollow//g'

echo "Do you want to know more? [y/n]" 
read more
if [ "$more" = "y" ]; then
curl -s https://www.merriam-webster.com/thesaurus/$word | grep -E "<title>" | sed 's/| Merriam-Webster Thesaurus<\/title>//g' | sed 's/[0-9]//g' | sed 's/<title>//g'  | sed 's/&amp;/|/g'

curl -s https://www.merriam-webster.com/thesaurus/$word | grep -E -m5 "content=" | tail -n1 | sed 's/<meta name="description" content="//g' | sed 's/">//g' | sed 's/<meta name="robots" content="noindex, nofollow//g' 


fi
